# Generated by Django 3.0.5 on 2020-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofbed', models.IntegerField()),
                ('decs', models.TextField()),
                ('price', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('postelcode', models.IntegerField()),
                ('img', models.IntegerField()),
            ],
        ),
    ]
