# Generated by Django 3.0.5 on 2020-05-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0005_auto_20200507_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qfield',
            old_name='qmaker_emial',
            new_name='owner_emial',
        ),
    ]
