# Generated by Django 3.0.5 on 2020-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0006_auto_20200507_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qfield',
            old_name='owner_emial',
            new_name='owner_email',
        ),
        migrations.AddField(
            model_name='qfield',
            name='your_email',
            field=models.EmailField(default=250, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qfield',
            name='owner_name',
            field=models.CharField(max_length=50),
        ),
    ]
