# Generated by Django 3.0.5 on 2020-05-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='qfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(max_length=254)),
                ('qmaker_emial', models.EmailField(max_length=254)),
                ('qmaker_name', models.CharField(max_length=50)),
                ('qmaker_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='owner_email',
            field=models.EmailField(default=5, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='owner_name',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
