# Generated by Django 3.0.5 on 2020-05-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0007_auto_20200508_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qfield',
            name='owner_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='qfield',
            name='your_email',
            field=models.CharField(max_length=50),
        ),
    ]
